### ISSUE TITLE
Accepting Pull Requests?

### ISSUE THREAD

**Issue by secondmanveran** [indielayer/ui#12]
The only PR I see here is one from January that still hasn't been accepted, are you guys taking PR's or should I not even waste my time?

I've done a ton of work updating this for my own use and if you'd like I'm happy to submit these changes in a large draft PR or a bunch of small one-off ones.

But if they're just gonna sit here un-merged for months I won't bother.

Thanks.

Nice work on this btw, it's a great start on a solid library.

**Comment by jpntex** [comment]
Hi there! Thank you for the kind words. Sorry for the late reply. I got a little side tracked with other shiny projects but I'll try my best to keep this library up-to-date and deliver new features. 

If you have improvement suggestions or features please let me know or open a PR.
