### ISSUE TITLE
Notification: i suggest a feature to keep open the notification when mouse hovered. 

### ISSUE THREAD

**Issue by KumJungMin** [indielayer/ui#83]
## Suggest
- i suggest a feature to keep open the notification when mouse hovered :)
- Similarly there is primeVue's `no-hover-pause` option. ([link](https://bootstrap-vue.org/docs/components/toast#auto-hide))
- if `no-hover-pause` option sets to true, pause a timeout when the mouse hovers the Notification.

(Video: The first notification will close after a certain period of time. The second notification remains open when the mouse is hovered over it.)

https://github.com/indielayer/ui/assets/37934668/e48644ce-bcbe-4884-b704-a86c8729a4cb

**Comment by jpntex** [comment]
Thanks @KumJungMin, added here: https://github.com/indielayer/ui/commit/b840ba7fabe277935bfed71191ebf967bce48fa7
