### ISSUE TITLE
Modal: the width of content increases when modal is opened.

### ISSUE THREAD

**Issue by KumJungMin** [indielayer/ui#84]
### Issue
- the width of content increases when modal is opened.

playground: https://codesandbox.io/p/devbox/agitated-thunder-vxrrgr?file=%2Fsrc%2FApp.vue%3A24%2C1

https://github.com/indielayer/ui/assets/37934668/e084ef98-743a-4abc-9c55-72456e52e396

<br/>

### Solution
- As the overflow of the body area changes from auto to hidden, the content width increases by the width of the scroll bar.
- This phenomenon can solve to add scroll width in paddingRight when the modal is opened.
- can i suggest fixed PR?

**Comment by jpntex** [comment]
Hi @KumJungMin, sorry for the delay, I missed the PR suggestion part.
I've added the fix with https://github.com/indielayer/ui/commit/2e95f8da039748fb28686e34868e0b6f0c789e12

Let me know if this covers what you were suggesting. Thanks
